# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-mkdocs-4rc0-test',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/nbdev-mkdocs-4rc0-test',
                'lib_path': 'nbdev_mkdocs_4rc0_test'},
  'syms': {'nbdev_mkdocs_4rc0_test.core': {'nbdev_mkdocs_4rc0_test.core.foo': ('core.html#foo', 'nbdev_mkdocs_4rc0_test/core.py')}}}
